### ISSUE TITLE
Can no longer download any TCGA data

### ISSUE THREAD

**Issue by JonnyTran** [compgenome365/TCGA-Assembler-2#1]
The error "Error in fromJSON(jsn) : no data to parse" keeps appearing when using the function DownloadMethylationData(), DownloadCNAData(), or any other download functions. Perhaps the GDC API has recently changed, and the TCGA-Assembler isn't getting a response from the server..

Tested on multiple machines on v2.0.5.

**Comment by compgenome365** [comment]
@JonnyTran 
Thanks for trying TCGA-Assembler 2!
You are right. This error is caused by change of GDC API. We just release a new version (2.0.6) at http://www.compgenome.org/TCGA-Assembler/

**Comment by JonnyTran** [comment]
Thanks for the quick update! I went on the website, and downloaded the TCGA-Assembler, however it looks like the file downloaded was still on version 2.0.5. Could you fix this?

**Comment by compgenome365** [comment]
Thank you! @JonnyTran 
Now the new version has been uploaded here (GitHub).
We are checking our server, maybe the older version is caused by cache.
